include:
   - infra.yaml
   - gpu.yaml
services:
  web:
    environment:
    - YOUR_DISCORD_TOKEN=${DISCORD_BOT_TOKEN}
    build: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /code