version: '3'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]
    volumes:
    - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
    - "4317:4317" # OTLP gRPC
    - "4318:4318" # OTLP HTTP
    # - "8889:8889"   # Prometheus exporter
    networks:
    - wis_net
  # Prometheus for metrics
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: always
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - wis_net

networks:
  wis_net:
    external: true

volumes: # prometheus_data:
