#include:
#   - infra.yaml
#   - gpu.yaml
services:
  wisbot:
    env_file:
    - path: ./wisbot.env
      required: true # default
    build: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /code