global:
  scrape_interval: 15s
  external_labels:
    origin_prometheus: prometheus01
remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: {{ secret.PROMETHEUS_USERNAME_WISBOT }}
      password: {{ secret.PROMETHEUS_PASSWORD_WISBOT }}
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
