receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  resource:
    attributes:
    - key: deployment.environment
      value: production
      action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: wisbot
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch, resource ]
      exporters: [ debug ]

    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch, resource ]
      exporters: [ prometheus, debug ]
    # logs:
    #   receivers: [otlp]
    #   processors: [memory_limiter, batch, resource]
    #   exporters: [loki]
