receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  resource:
    attributes:
    - key: deployment.environment
      value: production
      action: upsert

exporters:
  prometheus:
    endpoint: 192.168.1.14:9090/api/v1/push
    namespace: wisbot
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: http://192.168.1.14:3100/loki/api/v1/push
    tenant_id: "wisbot"
    labels:
      resource:
        service.name: "wisbot"


  # otlp:
  #   endpoint: 192.168.1.14:4317
  #   tls:
  #     insecure: true
  #   headers:
  #     x-scope-orgid: o11y

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch, resource ]
      exporters: [ debug ]

    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch, resource ]
      exporters: [ debug, prometheus ]
    
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch, resource ]
      exporters: [ debug, loki ]
