name: Deployment Script

on:
  push:
    branches:
    - main

jobs:
  deployment:
    runs-on: self-hosted # This specifies that the job should run on your self-hosted runner

    steps:
    - name: Clear Checkout Code Repository before new Checkout
      run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S rm -rf /home/uhstray/actions-runner/_work/WisBot/prometheus
    
    # - name: Re-create WisBot Directory
    #   run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S mkdir -p /home/uhstray/actions-runner/_work/WisBot/WisBot

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: 'true'
        repository: uhstray-io/WisBot
      
    - name: Change to WisBot Directory
      run: cd $GITHUB_WORKSPACE

    - name: Docker Down
      run: docker compose down

    - name: Append Secret to .env file
      run: printf "\nDISCORD_TOKEN_WISBOT=${{ secrets.DISCORD_TOKEN_WISBOT }}" >> .env

    - name: Print the contents of the .env file
      run: cat .env

    - name: Docker Build
      env:
        DISCORD_TOKEN_WISBOT: ${{ secrets.DISCORD_TOKEN_WISBOT }}
      run: docker build -t wisbot .

    - name: Docker Up
      run: docker compose up -d

