name: Deployment Wisbot Observability Agents

on:
  # push:
  #   branches:
  #   - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted # This specifies that the job should run on your self-hosted runner

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: uhstray-io/o11y
        
#    - name: Append Secret to .env file
#      run: printf "\nDISCORD_TOKEN_WISBOT=${{ secrets.DISCORD_TOKEN_WISBOT }}" >> .env

#    - name: Print the contents of the .env file
#      run: cat .env
    - name: Docker Down Prometheus
      run: cd ./prometheus && docker compose -f compose-remote.yml down 

    - name: Docker Up Prometheus
      run: cd ./prometheus && docker compose -f compose-remote.yml up -d

    - name: Docker Down Promtail
      run: cd ./promtail && docker compose -f compose-remote.yml down 

    - name: Docker Up Promtail
      run: cd ./promtail && docker compose -f compose-remote.yml up -d
