name: Deployment Script

on:
  push:
    branches:
    - main

jobs:
  deployment:
    runs-on: self-hosted # This specifies that the job should run on your self-hosted runner

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: uhstray-io/WisBot

    - name: Append Secret to .env file
      run: printf "\nDISCORD_TOKEN_WISBOT=${{ secrets.DISCORD_TOKEN_WISBOT }}" >> .env

    - name: Print the contents of the .env file
      run: cat .env

    - name: Docker Down
      run: docker compose down

    - name: Docker Build
      env:
        DISCORD_TOKEN_WISBOT: ${{ secrets.DISCORD_TOKEN_WISBOT }}
      run: docker build -t wisbot .

    - name: Docker Up
      run: docker compose up -d

