name: Instrument Linux Server with Prometheus & Node Exporter

on:
  push:
    branches:
      - observability-test

jobs:
  node_exporter:
    runs-on: self-hosted  # This specifies that the job should run on your self-hosted runner

    env:
      NODE_EXPORTER_VERSION: 1.8.2
      NODE_EXPORTER_HOME: /home/uhstray/node_exporter
      NODE_EXPORTER_DIR: /home/uhstray/node_exporter/node_exporter-1.8.2.linux-amd64
      NODE_EXPORTER_FILE: node_exporter-1.8.2.linux-amd64.tar.gz

    steps:
      # - name: Remove existing Wisbot _work directory
      # run: rm -rf ~/$USER/actions-runner/_work/WisBot
      # - name: Check the operating system of the runner
      #   run: echo "The operating system on the runner is $env:RUNNER_OS."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Node Exporter Directory
        run: mkdir -p $NODE_EXPORTER_DIR

      - name: Pull Node Exporter
        run: wget -nc https://github.com/prometheus/node_exporter/releases/download/v1.8.2/${{ env.NODE_EXPORTER_FILE }} -P $NODE_EXPORTER_HOME

      - name: Extract Node Exporter
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S tar xvfz $NODE_EXPORTER_HOME/$NODE_EXPORTER_FILE -C $NODE_EXPORTER_DIR

      - name: Copy the Node Exporter Service
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S cp o11y/node_exporter.service /etc/systemd/system/node_exporter.service

      - name: Reload the systemctl daemon
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S systemctl daemon-reload

      - name: Run the Node Exporter
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S service node_exporter start

      - name: Get the Node Exporter Status
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S systemctl status node_exporter
  
  prometheus:
    runs-on: self-hosted  # This specifies that the job should run on your self-hosted runner
    
    env:
      PROMETHEUS_VERSION: 2.53.3
      PROMETHEUS_PORT: 9090
      PROMETHEUS_HOME: /home/uhstray/prometheus
      PROMETHEUS_DIR: /home/uhstray/prometheus/prometheus-2.53.3.linux-amd64
      PROMETHEUS_FILE: prometheus-2.53.3.linux-amd64.tar.gz
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Prometheus Directory
        run: mkdir -p $PROMETHEUS_DIR

      - name: Pull Prometheus
        run: wget -nc https://github.com/prometheus/prometheus/releases/download/v2.53.3/${{ env.PROMETHEUS_FILE }} -P $PROMETHEUS_HOME

      - name: Extract Prometheus
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S tar xvf $PROMETHEUS_HOME/$PROMETHEUS_FILE -C $PROMETHEUS_DIR
      
      - name: Copy the Prometheus config file
        run: cp o11y/prometheus.yml $PROMETHEUS_HOME/prometheus.yml

      - name: Copy the Prometheus Service
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S cp o11y/prometheus.service /etc/systemd/system/prometheus.service

      - name: Reload the systemctl daemon
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S systemctl daemon-reload

      - name: Run Prometheus
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S service prometheus start

      - name: Get the Prometheus Status
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S service prometheus status

      - name: Open Prometheus Port with UFW
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S ufw allow $PROMETHEUS_PORT