name: Instrument Linux Server with Prometheus & Node Exporter

on:
  push:
    branches:
      - observability-test

jobs:
  node_exporter:
    runs-on: self-hosted  # This specifies that the job should run on your self-hosted runner

    env:
      NODE_EXPORTER_VERSION: 1.8.2
      NODE_EXPORTER_HOME: /home/uhstray/node_exporter
      NODE_EXPORTER_FILE: node_exporter-1.8.2.linux-amd64.tar.gz
      NODE_EXTRACTION_DIR: node_exporter-1.8.2.linux-amd64/
      NODE_EXPORTER_DIR: /home/uhstray/node_exporter/node_exporter-1.8.2.linux-amd64/
      OBSERVABILITY_DIR: o11y

    steps:
      # - name: Remove existing Wisbot _work directory
      # run: rm -rf ~/$USER/actions-runner/_work/WisBot
      # - name: Check the operating system of the runner
      #   run: echo "The operating system on the runner is $env:RUNNER_OS."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean directory before install
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S rm -rf $NODE_EXPORTER_DIR

      - name: Make Node Exporter Directory
        run: mkdir -p $NODE_EXPORTER_DIR

      - name: Pull Node Exporter
        run: wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/${{ env.NODE_EXPORTER_FILE }}

      - name: Extract Node Exporter
        run: tar -xvfz $NODE_EXPORTER_FILE

      - name: Upload Node Exporter TAR Archive Artifact to home directory
        uses: actions/upload-artifact@v4
        id: nodexporter-upload-step
        with:
          name: $NODE_EXTRACTION_DIR
          path: $NODE_EXPORTER_DIR

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.nodexporter-upload-step.outputs.artifact-id }}'

      - name: Copy the Node Exporter Service
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S cp $OBSERVABILITY_DIR/node_exporter.service /etc/systemd/system/node_exporter.service

      - name: Reload the systemctl daemon
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S systemctl daemon-reload

      - name: Run the Node Exporter
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S service node_exporter start

      - name: Get the Node Exporter Status
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S systemctl status node_exporter
  
  prometheus:
    runs-on: self-hosted  # This specifies that the job should run on your self-hosted runner
    needs: node_exporter
    env:
      PROMETHEUS_VERSION: 2.53.3
      PROMETHEUS_PORT: 9090
      PROMETHEUS_HOME: /home/uhstray/prometheus
      PROMETHEUS_SERVER_DIR: /home/uhstray/prometheus/prometheus-2.53.3.linux-amd64/
      PROMETHEUS_FILE: prometheus-2.53.3.linux-amd64.tar.gz
      PROM_EXTRACTION_DIR: prometheus-2.53.3.linux-amd64/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean directory before install
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S rm -rf $PROMETHEUS_DIR

      - name: Make Prometheus Directory
        run: mkdir -p $PROMETHEUS_DIR

      - name: Pull Prometheus
        run: wget https://github.com/prometheus/prometheus/releases/download/v2.53.3/${{ env.PROMETHEUS_FILE }}

      - name: Extract Prometheus
        run: tar -xvf $PROMETHEUS_FILE

      - name: Upload Prometheus TAR Archive Artifact to home directory
        uses: actions/upload-artifact@v4
        id: prometheus-upload-step
        with:
          name: $PROM_EXTRACTION_DIR
          path: $PROMETHEUS_DIR

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.prometheus-upload-step.outputs.artifact-id }}'

      - name: Copy the Prometheus config file
        run: cp o11y/prometheus.yml $PROMETHEUS_HOME/prometheus.yml

      - name: Update Prometheus.yml with the correct username
        run: sed 's/{{ secret.PROMETHEUS_USERNAME_WISBOT }}/${{ secrets.PROMETHEUS_USERNAME_WISBOT }}/g' $PROMETHEUS_HOME/prometheus.yml
      
      - name: Update Prometheus.yml with the correct password
        run: sed 's/{{ secret.PROMETHEUS_PASSWORD_WISBOT }}/${{ secrets.PROMETHEUS_PASSWORD_WISBOT }}/g' $PROMETHEUS_HOME/prometheus.yml

      - name: Copy the Prometheus Service
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S cp o11y/prometheus.service /etc/systemd/system/prometheus.service

      - name: Reload the systemctl daemon
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S systemctl daemon-reload

      - name: Run Prometheus
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S service prometheus start

      - name: Get the Prometheus Status
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S service prometheus status

      - name: Open Prometheus Port with UFW
        run: echo ${{ secrets.UHSTRAY_SUDO }} | sudo -S ufw allow $PROMETHEUS_PORT